[package]
name = "dirs"
version = "0.1.0"
edition = "2024"
license = "PHP-3.01"

[lib]
crate-type = ["cdylib"]

[dependencies]
dirs = "6.0.0"
ext-php-rs = "0.14.1"

[profile.release]
strip = "debuginfo"
